import type { MoodboardData } from '../types';

export const EXAMPLE_DATA: MoodboardData = {
  scenario: "Gashadokuro",
  contexte: "Demon Thrills · Contemporain · Iles Goto, Nagasaki · Zombiology",
  usage: "fiction",
  ambiance: "désolation sacrée, mémoire enfouie, lumière froide sur pierre volcanique",
  palette: "gris-vert, noir, ocre pâle, blanc cassé",
  images: [
    {
      id: 1,
      theme: "lieu_emblematique",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Nagasaki_1945_-_Before_and_after_%28adjusted%29.jpg/1280px-Nagasaki_1945_-_Before_and_after_%28adjusted%29.jpg",
      lieu: "Nagasaki, Japon",
      date: "9 aout 1945",
      taille: "full",
      tags: ["disparus", "sepulture-refusee", "colere-juste", "origine", "noms"],
      exclure: ["tourisme", "reconstruction", "couleur-vive"],
      intention: "on doit sentir le vide après la catastrophe",
      source_domaine: "upload.wikimedia.org",
      source_tier: 3,
      hotlink_safe: false,
    },
    {
      id: 2,
      theme: "ambiance_lumiere_saison",
      url: "https://voyapon.s3.amazonaws.com/wp-content/uploads/sites/2/2020/11/14012049/20200930-DSC_4345-1024x682-1.jpg",
      lieu: "Iles Goto, Nagasaki",
      date: "2020",
      taille: "half",
      tags: ["silence-insulaire", "isolement", "beaute-indifferente", "nuit-qui-vient"],
      exclure: ["foule", "enseigne-neon", "bateau-touristique"],
      intention: "on doit sentir l'isolement d'un archipel oublié",
      source_domaine: "voyapon.com",
      source_tier: 2,
      hotlink_safe: true,
    },
    {
      id: 3,
      theme: "detail_texture",
      url: "https://voyapon.s3.amazonaws.com/wp-content/uploads/sites/2/2020/11/14013441/20201001-Imochiura_Church_5-1024x682-1.jpg",
      lieu: "Eglise Imochiura, Goto, Nagasaki",
      date: "2020",
      taille: "half",
      tags: ["foi-cachee", "pierre-etrangere", "syncretisme", "denouement"],
      exclure: ["interieur-moderne", "visiteurs", "panneau"],
      intention: "on doit sentir le poids du secret dans la pierre",
      source_domaine: "voyapon.com",
      source_tier: 2,
      hotlink_safe: true,
    },
    {
      id: 4,
      theme: "contraste_tension",
      url: "https://voyapon.s3.amazonaws.com/wp-content/uploads/sites/2/2020/11/14013217/20200930-DJI_0095-1024x683-2.jpg",
      lieu: "Archipel des Goto, Nagasaki",
      date: "2020",
      taille: "tall",
      tags: ["bout-du-monde", "retour-coupe", "archipel-isole", "nul-part"],
      exclure: ["ville", "route", "infrastructure"],
      intention: "on doit sentir qu'il n'y a rien après",
      source_domaine: "voyapon.com",
      source_tier: 2,
      hotlink_safe: true,
    },
    {
      id: 5,
      theme: "element_humain_echelle",
      url: "https://voyapon.s3.amazonaws.com/wp-content/uploads/sites/2/2020/11/14012633/20200930-DSC_4714-Edit-1024x682-1.jpg",
      lieu: "Site kakure kirishitan, Goto",
      date: "2020",
      taille: "half",
      tags: ["morts-caches", "memoire-niee", "foi-souterraine", "temps-long"],
      exclure: ["musee", "vitrine", "explicatif"],
      intention: "on doit sentir la présence invisible des morts",
      source_domaine: "voyapon.com",
      source_tier: 2,
      hotlink_safe: true,
    },
    {
      id: 6,
      theme: "moment_activite",
      url: "https://www.nagasaki-tabinet.com/storage/special_feature_paragraphs/3972/responsive_images/aNidO86XVCrRFdl2xDaQdjoXZle8O4uMvTLR0BRe__1673_1096.jpeg",
      lieu: "Port de Nagasaki, Japon",
      date: "aujourd'hui",
      taille: "half",
      tags: ["depart", "suspension", "retour-coupe", "traversee"],
      exclure: ["croisiere", "foule", "commerce"],
      intention: "on doit sentir le départ sans retour",
      source_domaine: "nagasaki-tabinet.com",
      source_tier: 1,
      hotlink_safe: true,
    },
    {
      id: 7,
      theme: "lieu_emblematique",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Osezaki_lighthouse02s3200.jpg/1280px-Osezaki_lighthouse02s3200.jpg",
      lieu: "Cap Osezaki, Fukue, Goto",
      date: "aujourd'hui",
      taille: "full",
      tags: ["verticalite", "volcanique", "bout-du-monde", "sans-issue", "nul-part"],
      exclure: ["parking", "touristes", "panneau-info"],
      intention: "on doit sentir la fin de la terre",
      source_domaine: "upload.wikimedia.org",
      source_tier: 3,
      hotlink_safe: false,
    },
    {
      id: 8,
      theme: "contraste_tension",
      url: "https://www.encirclephotos.com/wp-content/uploads/Japan-Nagasaki-Peace-Park-Atomic-Bomb-Hypocenter-1440x961.jpg",
      lieu: "Parc de l'hypocentre, Nagasaki",
      date: "aujourd'hui",
      taille: "half",
      tags: ["vide", "sol-memoire", "colonne-invisible", "disparus"],
      exclure: ["ceremonie", "drapeau", "monument-clinquant"],
      intention: "on doit sentir l'absence absolue au sol",
      source_domaine: "encirclephotos.com",
      source_tier: 2,
      hotlink_safe: true,
    },
    {
      id: 9,
      theme: "detail_texture",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Dozakichurch01s3200.jpg/1280px-Dozakichurch01s3200.jpg",
      lieu: "Eglise Dozaki, Fukue, Goto",
      date: "construite 1908",
      taille: "square",
      tags: ["foi-cachee", "pierre-etrangere", "syncretisme", "denouement"],
      exclure: ["interieur", "messe", "fleurs"],
      intention: "on doit sentir la résistance silencieuse du bâtiment",
      source_domaine: "upload.wikimedia.org",
      source_tier: 3,
      hotlink_safe: false,
    },
  ],
};
